### ISSUE TITLE
genacl.py does not properly generate rules with "any"

### ISSUE THREAD

**Issue by AlekzNet** [AlekzNet/Cisco-ASA-ACL-toolkit#2]
"Any" is taken as a list [a, n, y], instead of one element.

**Comment by konst89** [comment]
![default](https://user-images.githubusercontent.com/46596066/51249719-5611d280-19be-11e9-9f10-7a6e06a91b74.PNG)
good day!
Please tell me what could be the problem?

**Comment by AlekzNet** [comment]
@konst89 - netaddr module is not installed. You can add it with this command:

```txt
pip install netaddr
```

**Comment by AlekzNet** [comment]
I will change genacl.py to add a better diagnostic/explanation.

**Comment by AlekzNet** [comment]
@konst89 - I think you are using an old version of genacl.py.

**Comment by AlekzNet** [comment]
The diagnostics have been fixed in the latest version.

**Comment by AlekzNet** [comment]
Fixed in https://github.com/AlekzNet/Cisco-ASA-ACL-toolkit/commit/7c132158905983fbce40b00812d84ab61b488e88
